//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_Compostable.Properties {
          
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
                       
        
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:58624/Service1.svc")]
        public string Team_Compostable_retrieve_Service1 {
            get {
                return ((string)(this["Team_Compostable_retrieve_Service1"]));
            }
        }
    }
}
