//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Statement.
        /// </summary>
        internal static string HeaderMission {
            get {
                return ResourceManager.GetString("HeaderMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string hHabout {
            get {
                return ResourceManager.GetString("hHabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to know.
        /// </summary>
        internal static string hHEverything {
            get {
                return ResourceManager.GetString("hHEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Living.
        /// </summary>
        internal static string hHGreen {
            get {
                return ResourceManager.GetString("hHGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Compostable!.
        /// </summary>
        internal static string hHMission {
            get {
                return ResourceManager.GetString("hHMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know ways you can prevent pollution, learn the consequences and how you stack up against everyone else.
        /// </summary>
        internal static string homeKnowW {
            get {
                return ResourceManager.GetString("homeKnowW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know your carbon footprint, earn points, and compete with friends.
        ///                You can find events and workshops around you to make yourself a little more environmentally friendly.
        /// </summary>
        internal static string homeKnowY {
            get {
                return ResourceManager.GetString("homeKnowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to provide a better way to inform people about Green Living.
        /// </summary>
        internal static string homeOur {
            get {
                return ResourceManager.GetString("homeOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Green Living?.
        /// </summary>
        internal static string homeWhat {
            get {
                return ResourceManager.GetString("homeWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Footprint.
        /// </summary>
        internal static string LabelCarbFoot {
            get {
                return ResourceManager.GetString("LabelCarbFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string LabelEvents {
            get {
                return ResourceManager.GetString("LabelEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string LabelHome {
            get {
                return ResourceManager.GetString("LabelHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution.
        /// </summary>
        internal static string LabelPollution {
            get {
                return ResourceManager.GetString("LabelPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Agreements.
        /// </summary>
        internal static string LabelTerms {
            get {
                return ResourceManager.GetString("LabelTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Compostable is a nonprofit group of individuals dedicated to utilizing modern web development skills,
        ///                 in order to design and develop a functional web page for those seeking to live a greener lifestyle.
        ///                 Our website will be able to be used for a multitude of tasks to promote green living..
        /// </summary>
        internal static string mission3 {
            get {
                return ResourceManager.GetString("mission3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse gases have been one of the most talked about issues in the 2000’s.
        ///                 Data, solutions and other information regarding them are wide and plentiful.
        ///                 We gather and collect data from various sources and determine ways that allow users to undergo greener living while still being able to maintain a comfortable lifestyle..
        /// </summary>
        internal static string mission4 {
            get {
                return ResourceManager.GetString("mission4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our primary concern is for the environment. Without a sustainable and clean environment, 
        ///                there may negative consequences to human health, energy supply, the ecosystem, etc.
        ///                In the long run this could affect future generations as well. 
        ///                Mission Compostable seeks to make people aware to this issue and encourages the people of today to leave less of a carbon footprint for the sake of the environment and future generations who live in it..
        /// </summary>
        internal static string mission7 {
            get {
                return ResourceManager.GetString("mission7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What We Do?.
        /// </summary>
        internal static string missionDo {
            get {
                return ResourceManager.GetString("missionDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Do It?.
        /// </summary>
        internal static string missionHow {
            get {
                return ResourceManager.GetString("missionHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Value do We Bring?.
        /// </summary>
        internal static string missionWhat {
            get {
                return ResourceManager.GetString("missionWhat", resourceCulture);
            }
        }
    }
}
